import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  TextInput,
  View,
} from 'react-native';
import { useRouter, Stack, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Animated, { FadeIn } from 'react-native-reanimated';
import { useTheme } from '../../src/theme/ThemeProvider';
import { GameOverModal } from '../../src/components/ui/GameOverModal';
import { ThemedText } from '../../src/components/ui/ThemedText';
import { Button } from '../../src/components/ui/Button';
import { recordGameResult } from '../../src/storage/scores';
import {
  type Board,
  type FoundWord,
  type Position,
  generateBoard,
  canTraceWord,
  traceWord,
  calculateScore,
} from '../../src/engines/boggle';
import { useResponsive } from '../../src/utils/layout';
import { haptics } from '../../src/utils/haptics';

const ROUND_DURATION_MS = 120_000; // 2 minutes

// ─── Fallback dictionary (common 3-8 letter English words) ─────────────────
// Used because src/data/dictionary.ts may not exist yet.
// The engine's isValidWord/submitWord rely on the DICTIONARY import, so we
// bypass the engine's validation and do our own here using this set.
const FALLBACK_DICTIONARY = new Set<string>([
  // 3-letter words
  'ACE','ACT','ADD','AGE','AGO','AID','AIM','AIR','ALL','AND','ANT','ANY','APE',
  'ARC','ARE','ARK','ARM','ART','ASH','ASK','ATE','AWE','AXE',
  'BAD','BAG','BAN','BAR','BAT','BED','BET','BIG','BIT','BOW','BOX','BOY','BUD',
  'BUG','BUN','BUS','BUT','BUY',
  'CAB','CAN','CAP','CAR','CAT','COP','COT','COW','CRY','CUB','CUP','CUR','CUT',
  'DAD','DAM','DAY','DEN','DEW','DID','DIG','DIM','DIP','DOC','DOG','DOT','DRY',
  'DUB','DUD','DUE','DUG','DUN','DUO','DYE',
  'EAR','EAT','EEL','EGG','ELF','ELK','ELM','EMU','END','ERA','EVE','EWE','EYE',
  'FAN','FAR','FAT','FAX','FED','FEW','FIG','FIN','FIT','FIX','FLY','FOB','FOE',
  'FOG','FOR','FOX','FRY','FUN','FUR',
  'GAB','GAG','GAP','GAS','GAY','GEL','GEM','GET','GIG','GIN','GNU','GOB','GOD',
  'GOT','GUM','GUN','GUT','GUY','GYM',
  'HAD','HAM','HAS','HAT','HAY','HEN','HER','HEW','HID','HIM','HIP','HIS','HIT',
  'HOB','HOG','HOP','HOT','HOW','HUB','HUE','HUG','HUM','HUT',
  'ICE','ICY','ILL','IMP','INK','INN','ION','IRE','IRK','ITS','IVY',
  'JAB','JAG','JAM','JAR','JAW','JAY','JET','JIG','JOB','JOG','JOT','JOY','JUG',
  'JUT',
  'KEG','KEN','KEY','KID','KIN','KIT',
  'LAB','LAD','LAG','LAP','LAW','LAY','LED','LEG','LET','LID','LIE','LIP','LIT',
  'LOG','LOT','LOW','LUG',
  'MAD','MAN','MAP','MAR','MAT','MAW','MAX','MAY','MEN','MET','MID','MIX','MOB',
  'MOD','MOM','MOP','MOW','MUD','MUG','MUM',
  'NAB','NAG','NAP','NET','NEW','NIL','NIT','NOB','NOD','NOR','NOT','NOW','NUB',
  'NUN','NUT',
  'OAK','OAR','OAT','ODD','ODE','OFF','OFT','OHM','OIL','OLD','ONE','OPT','ORB',
  'ORE','OUR','OUT','OWE','OWL','OWN',
  'PAD','PAN','PAP','PAR','PAT','PAW','PAY','PEA','PEG','PEN','PEP','PER','PET',
  'PEW','PIE','PIG','PIN','PIT','PLY','POD','POP','POT','POW','PRY','PUB','PUG',
  'PUN','PUP','PUS','PUT',
  'RAG','RAM','RAN','RAP','RAT','RAW','RAY','RED','REF','RIB','RID','RIG','RIM',
  'RIP','ROB','ROD','ROT','ROW','RUB','RUG','RUM','RUN','RUT','RYE',
  'SAC','SAD','SAG','SAP','SAT','SAW','SAY','SEA','SET','SEW','SHE','SHY','SIN',
  'SIP','SIR','SIS','SIT','SIX','SKI','SKY','SLY','SOB','SOD','SON','SOP','SOT',
  'SOW','SOY','SPA','SPY','STY','SUB','SUM','SUN','SUP',
  'TAB','TAD','TAG','TAN','TAP','TAR','TAT','TAX','TEA','TEN','THE','TIE','TIN',
  'TIP','TOE','TON','TOO','TOP','TOT','TOW','TOY','TUB','TUG','TUN','TWO',
  'URN','USE',
  'VAN','VAT','VET','VEX','VIA','VIE','VOW',
  'WAD','WAG','WAR','WAS','WAX','WAY','WEB','WED','WET','WHO','WIG','WIN','WIT',
  'WOE','WOK','WON','WOO','WOW',
  'YAK','YAM','YAP','YAW','YEA','YES','YET','YEW','YOU','YOW',
  'ZAP','ZEN','ZIP','ZIT','ZOO',
  // 4-letter words
  'ABLE','ACHE','ACID','ACRE','AGED','AIDE','ALLY','ALSO','ARCH','AREA','ARMY',
  'AUNT','AWAY','AXLE',
  'BACK','BADE','BAIL','BAIT','BAKE','BALD','BALE','BALL','BAND','BANE','BANG',
  'BANK','BARE','BARK','BARN','BASE','BATH','BEAD','BEAK','BEAM','BEAN','BEAR',
  'BEAT','BEEF','BEEN','BEER','BELL','BELT','BEND','BENT','BEST','BIKE','BILL',
  'BIND','BIRD','BITE','BLEW','BLOW','BLUE','BLUR','BOAT','BODY','BOLD','BOLT',
  'BOMB','BOND','BONE','BOOK','BOOM','BOOT','BORE','BORN','BOSS','BOTH','BOWL',
  'BRED','BREW','BULK','BULL','BUMP','BURN','BURY','BUSH','BUSY','BUZZ',
  'CAFE','CAGE','CAKE','CALF','CALL','CALM','CAME','CAMP','CANE','CAPE','CARD',
  'CARE','CART','CASE','CASH','CAST','CAVE','CELL','CHAT','CHIP','CHOP','CITY',
  'CLAD','CLAM','CLAP','CLAW','CLAY','CLIP','CLOT','CLUB','CLUE','COAL','COAT',
  'CODE','COIL','COIN','COLD','COLT','COMB','COME','CONE','COOK','COOL','COPE',
  'COPY','CORD','CORE','CORK','CORN','COST','COSY','COUP','CRAB','CREW','CROP',
  'CROW','CUBE','CULT','CURB','CURE','CURL','CUTE',
  'DALE','DAME','DAMP','DARE','DARK','DART','DASH','DATA','DATE','DAWN','DEAD',
  'DEAF','DEAL','DEAR','DEBT','DECK','DEED','DEEM','DEEP','DEER','DEMO','DENY',
  'DESK','DIAL','DICE','DIED','DIET','DINE','DIRT','DISC','DISH','DOCK','DOES',
  'DOME','DONE','DOOM','DOOR','DOSE','DOVE','DOWN','DRAW','DREW','DROP','DRUM',
  'DUAL','DUEL','DUKE','DULL','DUMB','DUMP','DUNE','DUNG','DUSK','DUST','DUTY',
  'EACH','EARN','EASE','EAST','EASY','EDGE','EDIT','ELSE','EMIT','ENVY','EPIC',
  'EVEN','EVER','EVIL','EXAM','EXIT','EYED','EYES',
  'FACE','FACT','FADE','FAIL','FAIR','FAKE','FALL','FAME','FANG','FARE','FARM',
  'FAST','FATE','FAWN','FEAR','FEAT','FEED','FEEL','FEET','FELL','FELT','FERN',
  'FILE','FILL','FILM','FIND','FINE','FIRE','FIRM','FISH','FIST','FLAG','FLAT',
  'FLAW','FLED','FLEW','FLIP','FLOCK','FLOW','FOAM','FOIL','FOLD','FOLK','FOND',
  'FOOD','FOOL','FOOT','FORD','FORE','FORK','FORM','FORT','FOUL','FOUR','FREE',
  'FROM','FUEL','FULL','FUME','FUND','FURY','FUSE','FUSS',
  'GAIN','GALE','GAME','GANG','GAPE','GARB','GATE','GAVE','GAZE','GEAR','GENE',
  'GIFT','GILD','GIRL','GIVE','GLAD','GLEN','GLOW','GLUE','GNAT','GNAW','GOAT',
  'GOES','GOLD','GOLF','GONE','GOOD','GORE','GRAB','GRAM','GRAY','GREW','GRID',
  'GRIM','GRIN','GRIP','GRIT','GROW','GULF','GUST',
  'HACK','HAIL','HAIR','HALE','HALF','HALL','HALT','HAND','HANG','HARD','HARE',
  'HARM','HARP','HATE','HAUL','HAVE','HAWK','HAZE','HEAD','HEAL','HEAP','HEAR',
  'HEAT','HEED','HEEL','HEIR','HELD','HELL','HELM','HELP','HERB','HERD','HERE',
  'HERO','HIGH','HIKE','HILL','HILT','HIND','HINT','HIRE','HISS','HIVE','HOAX',
  'HOLD','HOLE','HOME','HOOD','HOOK','HOPE','HORN','HOST','HOUR','HUGE','HULL',
  'HUNG','HUNT','HURL','HURT','HUSH','HYMN',
  'ICON','IDEA','IDLE','INCH','INTO','IRON','ISLE','ITEM',
  'JACK','JADE','JAIL','JAPE','JAZZ','JEAN','JEER','JERK','JEST','JINX','JOBS',
  'JOIN','JOKE','JOLT','JUMP','JUNE','JUNK','JURY','JUST','JUTE',
  'KEEL','KEEN','KEEP','KELP','KEPT','KICK','KILL','KIND','KING','KISS','KITE',
  'KNEE','KNEW','KNIT','KNOB','KNOT','KNOW',
  'LACE','LACK','LACY','LAID','LAIR','LAKE','LAMB','LAME','LAMP','LAND','LANE',
  'LARD','LARK','LASH','LASS','LAST','LATE','LAWN','LAZY','LEAD','LEAF','LEAK',
  'LEAN','LEAP','LEFT','LEND','LENS','LENT','LESS','LIED','LIEU','LIFE','LIFT',
  'LIKE','LIMB','LIME','LIMP','LINE','LINK','LION','LIST','LIVE','LOAD','LOAF',
  'LOAN','LOCK','LODE','LOFT','LONE','LONG','LOOK','LOOM','LORD','LORE','LOSE',
  'LOSS','LOST','LOUD','LOVE','LUCK','LUMP','LURE','LURK','LUSH','LUST',
  'MACE','MADE','MAIL','MAIN','MAKE','MALE','MALL','MALT','MANE','MANY','MARK',
  'MARS','MASK','MASS','MAST','MATE','MAZE','MEAL','MEAN','MEAT','MEET','MELD',
  'MELT','MEND','MENU','MERE','MESH','MESS','MILD','MILE','MILK','MILL','MIME',
  'MIND','MINE','MINT','MISS','MIST','MOAN','MOAT','MOCK','MODE','MOLD','MOLE',
  'MOLT','MOOD','MOON','MOOR','MOPE','MORE','MOSS','MOST','MOTH','MOVE','MUCH',
  'MUCK','MULE','MULL','MURK','MUSE','MUSH','MUST','MUTE',
  'NAIL','NAME','NAPE','NAVY','NEAR','NEAT','NECK','NEED','NEST','NEWS','NEXT',
  'NICE','NINE','NODE','NONE','NOON','NORM','NOSE','NOTE','NOUN','NUDE','NULL',
  'NUMB',
  'OATH','OBEY','ODDS','OMEN','OMIT','ONCE','ONLY','ONTO','OOZE','OPEN','ORAL',
  'ORCA','OURS','OUST','OVEN','OVER','OWED','OXEN',
  'PACE','PACK','PAGE','PAID','PAIL','PAIN','PAIR','PALE','PALM','PANE','PANT',
  'PARK','PART','PASS','PAST','PATH','PAVE','PEAK','PEAL','PEAR','PEAT','PECK',
  'PEEL','PEER','PELT','PERK','PEST','PICK','PIER','PILE','PINE','PINK','PIPE',
  'PLAN','PLAY','PLEA','PLOD','PLOT','PLOW','PLUG','PLUM','PLUS','POCK','POEM',
  'POET','POKE','POLE','POLL','POLO','POMP','POND','POOL','POOR','POPE','PORE',
  'PORK','PORT','POSE','POST','POUR','PRAY','PREY','PROP','PROW','PULL','PULP',
  'PUMP','PURE','PUSH',
  'RACE','RACK','RAFT','RAGE','RAID','RAIL','RAIN','RAKE','RAMP','RANG','RANK',
  'RARE','RASH','RATE','RAVE','READ','REAL','REAP','REAR','REEF','REEL','REIN',
  'RELY','REND','RENT','REST','RICE','RICH','RIDE','RIFT','RILE','RIND','RING',
  'RIOT','RISE','RISK','ROAD','ROAM','ROAR','ROBE','ROCK','RODE','ROLE','ROLL',
  'ROOF','ROOM','ROOT','ROPE','ROSE','ROVE','RUDE','RUIN','RULE','RUNG','RUSE',
  'RUSH','RUST',
  'SACK','SAFE','SAGE','SAID','SAIL','SAKE','SALE','SALT','SAME','SAND','SANE',
  'SANG','SANK','SAVE','SEAL','SEAM','SEAR','SEAT','SECT','SEED','SEEK','SEEM',
  'SEEN','SELF','SELL','SEND','SENT','SEWN','SHED','SHIN','SHIP','SHOE','SHOP',
  'SHOT','SHOW','SHUT','SICK','SIDE','SIFT','SIGH','SIGN','SILK','SILL','SILT',
  'SING','SINK','SIRE','SITE','SIZE','SKID','SKIM','SKIN','SKIP','SKIT','SLAB',
  'SLAG','SLAM','SLAP','SLAT','SLAW','SLAY','SLED','SLEW','SLID','SLIM','SLIP',
  'SLIT','SLOB','SLOP','SLOT','SLOW','SLUG','SLUM','SMOG','SNAP','SNOB','SNOW',
  'SNUB','SNUG','SOAK','SOAP','SOAR','SOCK','SOFT','SOIL','SOLD','SOLE','SOME',
  'SONG','SOON','SOOT','SORE','SORT','SOUL','SOUR','SPAN','SPAR','SPEC','SPED',
  'SPIN','SPIT','SPOT','SPUR','STAB','STAG','STAR','STAY','STEM','STEP','STEW',
  'STIR','STOP','STOW','STUB','STUD','STUN','SUCH','SUIT','SULK','SURE','SURF',
  'SWAN','SWAP','SWIM',
  'TACK','TACT','TAIL','TAKE','TALE','TALK','TALL','TAME','TANK','TAPE','TARN',
  'TART','TASK','TEAM','TEAR','TELL','TEND','TENS','TENT','TERM','TEST','TEXT',
  'THAN','THAT','THEM','THEN','THEY','THIN','THIS','TIDE','TIDY','TIED','TIER',
  'TILE','TILL','TILT','TIME','TINE','TINY','TIRE','TOAD','TOIL','TOLD','TOLL',
  'TOMB','TONE','TOOK','TOOL','TOPS','TORE','TORN','TOUR','TOWN','TRAP','TRAY',
  'TREE','TREK','TRIM','TRIO','TRIP','TROD','TROT','TRUE','TUBE','TUCK','TUFT',
  'TUNA','TUNE','TURF','TURN','TUSK','TWIN','TYPE',
  'UGLY','UNDO','UNIT','UNTO','UPON','URGE','USED','USER',
  'VAIN','VALE','VANE','VARY','VASE','VAST','VEIL','VEIN','VENT','VERB','VERY',
  'VEST','VETO','VICE','VIDE','VIEW','VINE','VOID','VOLT','VOTE',
  'WADE','WAGE','WAIL','WAIT','WAKE','WALK','WALL','WAND','WANT','WARD','WARM',
  'WARN','WARP','WART','WARY','WASH','WASP','WAVE','WAVY','WAXY','WEAK','WEAN',
  'WEAR','WEED','WEEK','WEEP','WELD','WELL','WENT','WEPT','WERE','WEST','WHAT',
  'WHEN','WHIM','WHIP','WHOM','WICK','WIDE','WIFE','WILD','WILL','WILT','WILY',
  'WIND','WINE','WING','WINK','WIPE','WIRE','WISE','WISH','WITH','WITS','WOKE',
  'WOLF','WOMB','WOOD','WOOL','WORD','WORE','WORK','WORM','WORN','WOVE','WRAP',
  'WREN',
  'YALE','YANK','YARD','YARN','YEAR','YELL','YOUR',
  'ZEAL','ZERO','ZEST','ZINC','ZONE','ZOOM',
  // 5-letter words
  'ABIDE','ABOUT','ABOVE','ABUSE','ACTOR','ACUTE','ADMIT','ADOPT','ADULT','AFTER',
  'AGAIN','AGENT','AGILE','AGING','AGREE','AHEAD','AISLE','ALARM','ALIEN','ALIGN',
  'ALIVE','ALLEY','ALLOW','ALLOY','ALONG','ALTER','AMPLE','ANGEL','ANGER','ANGLE',
  'ANGRY','ANKLE','APART','APPLE','APPLY','ARENA','ARGUE','ARISE','ARMOR','ARROW',
  'ASIDE','ASSET','ATLAS','ATTIC','AVOID','AWAKE','AWARD','AWARE','AWFUL',
  'BADGE','BADLY','BAKER','BARON','BASIC','BASIN','BASIS','BATCH','BEACH','BEAST',
  'BEGIN','BEING','BELOW','BENCH','BLACK','BLADE','BLAME','BLAND','BLANK','BLAST',
  'BLAZE','BLEED','BLEND','BLESS','BLIND','BLISS','BLOCK','BLOND','BLOOM','BLOWN',
  'BLUES','BLUNT','BOARD','BOAST','BONUS','BOUND','BRAIN','BRAND','BRAVE','BREAD',
  'BREAK','BREED','BRICK','BRIDE','BRIEF','BRING','BROAD','BROKE','BROOK','BROWN',
  'BRUSH','BUILD','BUILT','BURST','BUYER',
  'CABIN','CABLE','CAMEL','CANDY','CARGO','CARRY','CATCH','CAUSE','CEASE','CHAIN',
  'CHAIR','CHALK','CHARM','CHART','CHASE','CHEAP','CHECK','CHEEK','CHEER','CHESS',
  'CHEST','CHIEF','CHILD','CHINA','CHORD','CHUNK','CIVIL','CLAIM','CLASH','CLASS',
  'CLEAN','CLEAR','CLERK','CLICK','CLIFF','CLIMB','CLING','CLOCK','CLONE','CLOSE',
  'CLOTH','CLOUD','CLOWN','COACH','COAST','COLOR','COMET','CORAL','COULD','COUNT',
  'COURT','COVER','CRACK','CRAFT','CRANE','CRASH','CRAZY','CREAM','CREST','CRIME',
  'CROSS','CROWD','CROWN','CRUDE','CRUSH','CURVE','CYCLE',
  'DAILY','DANCE','DEALT','DEATH','DEBUT','DECAY','DELAY','DEMON','DENSE','DEPOT',
  'DEPTH','DERBY','DEVIL','DIARY','DIRTY','DITCH','DIZZY','DODGE','DOUBT','DOUGH',
  'DOZEN','DRAFT','DRAIN','DRAKE','DRAMA','DRANK','DRAWN','DREAM','DRESS','DRIED',
  'DRIFT','DRILL','DRINK','DRIVE','DROIT','DRONE','DROOL','DROVE','DRUNK','DRYER',
  'DWARF','DWELL',
  'EAGER','EARLY','EARTH','EIGHT','ELDER','ELECT','ELITE','EMPTY','ENEMY','ENJOY',
  'ENTER','ENTRY','EQUAL','ERROR','EVENT','EVERY','EXACT','EXERT','EXILE','EXIST',
  'EXTRA',
  'FABLE','FACET','FAINT','FAITH','FALSE','FANCY','FATAL','FAULT','FEAST','FENCE',
  'FERRY','FEVER','FIBER','FIELD','FIERY','FIFTH','FIFTY','FIGHT','FINAL','FLAME',
  'FLASH','FLASK','FLEET','FLESH','FLICK','FLOAT','FLOCK','FLOOD','FLOOR','FLORA',
  'FLOUR','FLUID','FLUSH','FLUTE','FOCUS','FORCE','FORGE','FORTY','FORUM','FOUND',
  'FRAME','FRANK','FRAUD','FRESH','FRONT','FROST','FROZE','FRUIT','FULLY',
  'GIANT','GIVEN','GLARE','GLASS','GLEAM','GLOBE','GLOOM','GLORY','GLOSS','GLOVE',
  'GOING','GRACE','GRADE','GRAIN','GRAND','GRANT','GRAPE','GRAPH','GRASP','GRASS',
  'GRAVE','GRAVEL','GRAZE','GREAT','GREED','GREEN','GREET','GRIEF','GRIND','GROAN',
  'GROOM','GROSS','GROUP','GROVE','GROWN','GUARD','GUESS','GUEST','GUIDE','GUILT',
  'HAIRY','HAPPY','HARSH','HASTE','HAVEN','HEART','HEAVY','HENCE','HINGE','HOBBY',
  'HONEY','HONOR','HORSE','HOTEL','HOUSE','HUMAN','HUMOR','HURRY',
  'IDEAL','IMAGE','IMPLY','INDEX','INDIE','INFER','INNER','INPUT','IRONY','ISSUE',
  'IVORY',
  'JEWEL','JOINT','JOKER','JUDGE','JUICE','JUICY',
  'KNACK','KNEEL','KNIFE','KNOCK','KNOWN',
  'LABEL','LABOR','LARGE','LASER','LATER','LAUGH','LAYER','LEARN','LEASE','LEAST',
  'LEAVE','LEVEL','LIGHT','LIKEN','LIMIT','LINEN','LIVER','LOCAL','LODGE','LOGIC',
  'LONELY','LOOSE','LOVER','LOWER','LOYAL','LUCKY','LUNAR','LUNCH',
  'MAGIC','MAJOR','MAKER','MANOR','MAPLE','MARCH','MATCH','MAYOR','MEDIA','MERCY',
  'MERGE','MERIT','METAL','MIGHT','MINOR','MINUS','MIRTH','MODEL','MONEY','MONTH',
  'MORAL','MOTOR','MOUNT','MOUSE','MOUTH','MOVED','MOVER','MOVIE','MUDDY','MURAL',
  'MUSIC','NAIVE','NERVE','NEVER','NIGHT','NOBLE','NOISE','NORTH','NOTED','NOVEL',
  'NURSE',
  'OCEAN','OFFER','OFTEN','OLIVE','ONSET','OPERA','ORBIT','ORDER','OTHER','OUTER',
  'OWNER','OXIDE',
  'PANEL','PANIC','PARTY','PASTE','PATCH','PAUSE','PEACE','PEARL','PEDAL','PENNY',
  'PHASE','PHONE','PHOTO','PIANO','PIECE','PILOT','PITCH','PIXEL','PIZZA','PLACE',
  'PLAIN','PLANE','PLANT','PLATE','PLAZA','PLEAD','PLEAT','PLUCK','PLUMB','PLUME',
  'PLUMP','POINT','POLAR','PORCH','POSER','POUND','POWER','PRESS','PRICE','PRIDE',
  'PRIME','PRINT','PRIOR','PRIZE','PROBE','PRONE','PROOF','PROUD','PROVE','PULSE',
  'PUNCH','PUPIL','PURSE','PUSHY',
  'QUEEN','QUEST','QUEUE','QUICK','QUIET','QUOTA','QUOTE',
  'RADAR','RAISE','RALLY','RANCH','RANGE','RAPID','RATIO','REACH','REALM','REBEL',
  'REFER','REIGN','RELAX','REMIT','REPLY','RIDER','RIDGE','RIFLE','RIGHT','RIGID',
  'RIGOR','RINSE','RIVAL','RIVER','ROBIN','ROBOT','ROCKY','ROUGE','ROUGH','ROUND',
  'ROUTE','ROYAL','RULER','RURAL',
  'SADLY','SAINT','SAUCE','SCALE','SCARE','SCENE','SCENT','SCOPE','SCORE','SCOUT',
  'SCRAP','SENSE','SERVE','SEVEN','SHADE','SHALL','SHAME','SHAPE','SHARE','SHARK',
  'SHARP','SHEAR','SHEEP','SHEER','SHEET','SHELF','SHELL','SHIFT','SHINE','SHIRT',
  'SHOCK','SHORE','SHORT','SHOUT','SIGHT','SINCE','SIXTH','SIXTY','SKILL','SKULL',
  'SLASH','SLATE','SLAVE','SLEEP','SLICE','SLIDE','SLOPE','SMALL','SMART','SMELL',
  'SMILE','SMOKE','SNACK','SNAKE','SOLAR','SOLID','SOLVE','SORRY','SOUND','SOUTH',
  'SPACE','SPARE','SPARK','SPEAK','SPEAR','SPEED','SPELL','SPEND','SPICE','SPIKE',
  'SPINE','SPITE','SPOKE','SPOON','SPORT','SPRAY','SQUAD','STAFF','STAGE','STAIN',
  'STAIR','STAKE','STALE','STALL','STAMP','STAND','STARE','START','STATE','STAVE',
  'STAYS','STEAK','STEAL','STEAM','STEEL','STEEP','STEER','STERN','STICK','STIFF',
  'STILL','STING','STOCK','STOLE','STONE','STOOD','STOOL','STORE','STORM','STORY',
  'STOUT','STOVE','STRAP','STRAW','STRAY','STRIP','STUCK','STUFF','STUMP','STUNG',
  'STUNT','STYLE','SUGAR','SUITE','SUNNY','SUPER','SURGE','SWAMP','SWARM','SWEAR',
  'SWEAT','SWEEP','SWEET','SWEPT','SWIFT','SWING','SWORD',
  'TABLE','TASTE','TEACH','TEETH','TEMPO','TENSE','THANK','THEFT','THEME','THERE',
  'THICK','THIEF','THING','THINK','THIRD','THORN','THOSE','THREE','THREW','THROW',
  'THUMB','TIGER','TIGHT','TIMER','TITLE','TODAY','TOKEN','TOTAL','TOUCH','TOUGH',
  'TOWER','TOXIC','TRACE','TRACK','TRADE','TRAIL','TRAIN','TRAIT','TRASH','TREAT',
  'TREND','TRIAL','TRIBE','TRICK','TRIED','TROOP','TRUCK','TRULY','TRUMP','TRUNK',
  'TRUST','TRUTH','TUMOR','TUNER','TWICE','TWIST',
  'ULTRA','UNCLE','UNDER','UNIFY','UNION','UNITE','UNITY','UNTIL','UPPER','UPSET',
  'URBAN','USUAL','UTTER',
  'VAGUE','VALID','VALUE','VAULT','VERSE','VIDEO','VIGOR','VINYL','VIRAL','VIRUS',
  'VISIT','VISTA','VITAL','VIVID','VOCAL','VOICE','VOTER',
  'WAIST','WASTE','WATCH','WATER','WEARY','WEAVE','WEDGE','WHEAT','WHEEL','WHERE',
  'WHILE','WHIRL','WHITE','WHOLE','WHOSE','WIDOW','WIDTH','WITCH','WORLD','WORRY',
  'WORSE','WORST','WORTH','WOULD','WOUND','WRATH','WRITE','WRONG','WROTE',
  'YACHT','YIELD','YOUNG','YOUTH',
  'ZONES',
  // 6-letter words
  'ABSORB','ACCENT','ACCEPT','ACCESS','ACROSS','ACTION','ACTUAL','ADJUST','ADMIRE',
  'AFFIRM','AFFORD','AGENDA','ALMOST','AMOUNT','ANNUAL','ANSWER','ANYONE','ANYWAY',
  'APPEAL','APPEAR','ARTIST','ASPECT','ASSIGN','ASSIST','ASSUME','ATTACH','ATTACK',
  'ATTEND','AUGUST',
  'BATTLE','BEAUTY','BECAME','BECOME','BEFORE','BEHALF','BEHIND','BELONG','BESIDE',
  'BETTER','BEYOND','BITTER','BLANCH','BOTHER','BOTTOM','BOUNCE','BRANCH','BREATH',
  'BRIDGE','BRIGHT','BROKEN','BRONZE','BUBBLE','BUDGET','BURDEN','BUTLER','BUTTER',
  'CAMERA','CANCEL','CARBON','CAREER','CASTLE','CAUGHT','CENTER','CHANCE','CHANGE',
  'CHARGE','CHOSEN','CHURCH','CIRCLE','CLEVER','CLIENT','CLOSED','CLOSET','COFFEE',
  'COLUMN','COMBAT','COMMON','COMPLY','COOKIE','CORNER','COSTLY','COTTON','COUNTY',
  'COUPLE','COURSE','COUSIN','CREATE','CREDIT','CRISIS','CUSTOM','DANGER','DEALER',
  'DEBATE','DECADE','DECIDE','DEFEAT','DEFEND','DEFINE','DEGREE','DEMAND','DENIAL',
  'DEPEND','DEPLOY','DESERT','DESIGN','DESIRE','DETAIL','DETECT','DEVICE','DIFFER',
  'DINNER','DIRECT','DIVINE','DOMAIN','DOUBLE','DRIVER','DURING',
  'EASILY','EDITOR','EFFECT','EFFORT','EIGHTH','EMERGE','EMPIRE','EMPLOY','ENABLE',
  'ENDING','ENERGY','ENGAGE','ENGINE','ENOUGH','ENSURE','ENTIRE','ENTITY','ESCAPE',
  'ESTATE','ETHNIC','EVOLVE','EXCEED','EXCEPT','EXCESS','EXCUSE','EXEMPT','EXPAND',
  'EXPECT','EXPERT','EXPORT','EXTEND','EXTENT','FABRIC',
  'FACTOR','FAIRLY','FALLEN','FAMILY','FAMOUS','FARMER','FATHER','FATHOM','FAVORS',
  'FELLOW','FEMALE','FIGURE','FILTER','FINGER','FINISH','FISCAL','FLIGHT','FLOWER',
  'FOLLOW','FOREST','FORGET','FORMAT','FORMER','FOSTER','FOURTH','FREEZE','FRIEND',
  'FROZEN','FULFILL','FUTURE',
  'GAINED','GALAXY','GARDEN','GATHER','GENDER','GENTLE','GIFTED','GLOBAL','GOLDEN',
  'GOVERN','GROWTH','GUILTY',
  'HANDLE','HAPPEN','HARDLY','HAZARD','HEALTH','HEAVEN','HIDDEN','HIGHLY','HONEST',
  'HORROR','HUNGER','HUNTER',
  'IGNORE','IMMUNE','IMPACT','IMPORT','IMPOSE','INCOME','INDEED','INDOOR','INFORM',
  'INJURY','INSECT','INSIDE','INSIST','INTACT','INTEND','INTENT','INVADE','INVEST',
  'ISLAND','ITSELF',
  'JACKET','JUNIOR','JUNGLE','JUSTICE',
  'KINDLY','KNIGHT','LADDER','LATELY','LAUNCH','LAWFUL','LAWYER','LAYOUT','LEADER',
  'LENGTH','LESSON','LETTER','LIKELY','LINING','LIQUID','LISTEN','LITTLE','LIVELY',
  'LIVING','LONELY','LONGER','LUXURY',
  'MAINLY','MANAGE','MANNER','MANUAL','MARGIN','MARINE','MARKET','MASTER','MATTER',
  'MEDIUM','MEMBER','MEMORY','MENTAL','MENTOR','METHOD','MIDDLE','MIGHTY','MINUTE',
  'MIRROR','MOBILE','MODEST','MOMENT','MOSTLY','MOTHER','MOTION','MUSEUM','MUTUAL',
  'NARROW','NATION','NATURE','NEARBY','NEARLY','NEATLY','NICELY','NORMAL','NOTICE',
  'NOTION','NUMBER',
  'OBJECT','OBTAIN','OCCUPY','OFFEND','OFFICE','ONLINE','OPPOSE','OPTION','ORANGE',
  'ORIGIN','OUTPUT',
  'PALACE','PARENT','PARTLY','PATROL','PATRON','PEOPLE','PERIOD','PERMIT','PERSON',
  'PHRASE','PICKER','PLANET','PLAYER','PLEASE','PLEDGE','PLENTY','POCKET','POETRY',
  'POISON','POLICE','POLICY','POLISH','PORTAL','POSTER','POTATO','POWDER','PRAISE',
  'PRAYER','PREFER','PRINCE','PRISON','PROFIT','PROMPT','PROPER','PROVEN','PUBLIC',
  'PUNISH','PURSUE','PUZZLE',
  'RANDOM','RARELY','RATING','RATHER','READER','REASON','RECENT','RECORD','REDUCE',
  'REFORM','REGARD','REGIME','REGION','REJECT','RELATE','RELIEF','REMAIN','REMEDY',
  'REMIND','REMOTE','REMOVE','RENDER','RENEW','RENTAL','REPAIR','REPEAT','REPORT',
  'RESCUE','RESIST','RESORT','RESULT','RETAIL','RETAIN','RETIRE','RETURN','REVEAL',
  'REVIEW','REVOLT','REWARD','RHYTHM','ROBUST','ROSTER','RULING',
  'SACRED','SAFELY','SAFETY','SALARY','SAMPLE','SCHEME','SCHOOL','SCREEN','SCRIPT',
  'SEARCH','SEASON','SECOND','SECRET','SECTOR','SECURE','SELECT','SELLER','SENIOR',
  'SERIES','SETTLE','SEVERE','SHADOW','SHAPED','SHELVE','SHIELD','SIGNAL','SILENT',
  'SILVER','SIMPLE','SIMPLY','SINGLE','SISTER','SLIGHT','SMOOTH','SOCIAL','SOFTLY',
  'SOLELY','SOLEMN','SOUGHT','SOURCE','SPHERE','SPIRIT','SPREAD','SPRING','SQUARE',
  'STABLE','STATUS','STEADY','STOLEN','STRAIN','STRAND','STREAM','STREET','STRICT',
  'STRIKE','STRING','STRIPE','STROKE','STRONG','SUBMIT','SUDDEN','SUFFER','SUMMER',
  'SUMMIT','SUPPLY','SURELY','SURVEY','SWITCH','SYMBOL','SYSTEM',
  'TACKLE','TALENT','TARGET','TEMPLE','TENANT','TENDER','TERROR','THANKS','THEORY',
  'THIRTY','THREAT','THRIVE','THRONE','TICKET','TIMBER','TISSUE','TONGUE','TOWARD',
  'TRAVEL','TREATY','TRIBAL','TRICKY','TROPHY','TUNNEL','TWELVE','TWENTY',
  'UNFAIR','UNIQUE','UNLIKE','UNVEIL','UPDATE','UPHOLD','USEFUL',
  'VACUUM','VALLEY','VARIED','VENDOR','VENTURE','VESSEL','VICTIM','VISION','VISUAL',
  'VOLUME',
  'WALKER','WANDER','WARMTH','WEALTH','WEAPON','WEEKLY','WEIGHT','WIDELY','WINDOW',
  'WINNER','WINTER','WISDOM','WITHIN','WONDER','WOODEN','WORKER','WORTHY','WRITER',
  // 7-letter words
  'ABILITY','ABOLISH','ABSENCE','ACADEMY','ACCOUNT','ACHIEVE','ACQUIRE','ADDRESS',
  'ADVANCE','ALCHEMY','ALREADY','AMAZING','ANCIENT','ANOTHER','ANXIETY','APPLIED',
  'ARRANGE','ARTICLE','ASSAULT','ATTEMPT','ATTRACT','AUCTION','AVERAGE',
  'BALANCE','BANKING','BARGAIN','BARRIER','BATTERY','BEARING','BENEATH','BENEFIT',
  'BESIDES','BETWEEN','BILLION','BROTHER','CABINET','CALIBER','CAPABLE','CAPITAL',
  'CAPTAIN','CAPTURE','CAUTION','CENTRAL','CENTURY','CERTAIN','CHAMBER','CHAPTER',
  'CHARTER','CHICKEN','CHRONIC','CIRCUIT','CITIZEN','CLASSIC','CLIMATE','CLUSTER',
  'CLOSELY','CLOSEST','CLOSURE','COLLECT','COLLEGE','COMFORT','COMMAND','COMMENT',
  'COMPACT','COMPANY','COMPARE','COMPEL','COMPETE','COMPLEX','COMPUTE','CONCERN',
  'CONDUCT','CONFIRM','CONNECT','CONSENT','CONSIST','CONTACT','CONTAIN','CONTENT',
  'CONTEST','CONTEXT','CONTROL','CONVERT','CORRECT','COTTAGE','COUNCIL','COUNTER',
  'COUNTRY','COURAGE','CRUCIAL','CURRENT','CUSTOMS','DEFENSE','DEFICIT','DELIVER',
  'DEPOSIT','DESPITE','DESTINY','DEVELOP','DIGITAL','DISPLAY','DISPUTE','DISTANT',
  'DISTURB','DIVERSE','CHARTER','COMPANY',
  'ECOLOGY','ECONOMY','EDITION','EDUCATE','ELDERLY','ELEMENT','EMBRACE','EMOTION',
  'EMPEROR','ENDLESS','ENHANCE','ESSENCE','ETERNAL','EVENING','EVIDENT','EXAMINE',
  'EXAMPLE','EXCITED','EXECUTE','EXHIBIT','EXPENSE','EXPLAIN','EXPLOIT','EXPLORE',
  'EXPRESS','EXTREME','FACTORY','FAILURE','FANTASY','FASHION','FEATURE','FICTION',
  'FIGHTER','FINANCE','FINDING','FOREIGN','FOREVER','FORMULA','FORTUNE','FORWARD',
  'FOUNDED','FREEDOM','FULFILL','FURTHER','GALLERY','GENERAL','GENUINE','GESTURE',
  'GLIMPSE','HABITAT','HALFWAY','HANDMADE','HANDFUL','HEALTHY','HELPFUL','HIGHWAY',
  'HIMSELF','HISTORY','HOLIDAY','HOUSING','HOWEVER','HUNDRED','HUSBAND','ILLEGAL',
  'IMAGINE','IMMENSE','INITIAL','INQUIRY','INSIGHT','INSTALL','INSTANT','INTENSE',
  'INTERIM','JOURNEY','JUSTICE','KINGDOM','KITCHEN','LACKING','LANDING','LARGELY',
  'LASTING','LEARNED','LECTURE','LIBERAL','LIBERTY','LIMITED','LOGICAL','LOYALTY',
  'MACHINE','MANKIND','MASSIVE','MASTERY','MEETING','MENTION','MESSAGE','MINERAL',
  'MINIMUM','MIRACLE','MISSION','MIXTURE','MONITOR','MONSTER','MONTHLY','MORNING',
  'MUSICAL','MYSTERY','NATURAL','NEGLECT','NEITHER','NERVOUS','NETWORK','NEUTRAL',
  'NOTABLE','NOTHING','NUCLEAR','OBESITY','OBSERVE','OBVIOUS','OFFENSE','OFFICER',
  'ONGOING','OPENING','OPERATE','OPINION','ORGANIC','OUTCOME','OUTDOOR','OUTLOOK',
  'OVERALL','OVERLAP','OVERSEE','PAINFUL','PARTIAL','PARTNER','PASSAGE','PASSION',
  'PATIENT','PATTERN','PAYMENT','PENALTY','PENSION','PERCENT','PERFECT','PIONEER',
  'PLASTIC','PLEDGE','POINTED','POLITIC','POPULAR','PORTION','POSSESS','POTTERY',
  'POVERTY','PRECISE','PREDICT','PREMIER','PREPARE','PRESENT','PREVENT','PRIMARY',
  'PRIVACY','PRIVATE','PROBLEM','PROCEED','PROCESS','PRODUCE','PRODUCT','PROFILE',
  'PROGRAM','PROJECT','PROMISE','PROMOTE','PROPHET','PROTECT','PROTEIN','PROTEST',
  'PROVIDE','PUBLISH','PURPOSE','QUALITY','QUARTER','QUICKLY','RADICAL','READILY',
  'REALITY','REBUILD','RECEIVE','RECOVER','REFLECT','REFORMS','REFUGEE','RELATED',
  'RELEASE','REMAINS','REMOVAL','REPLACE','REQUEST','REQUIRE','RESERVE','RESOLVE',
  'RESPECT','RESPOND','RESTORE','RETREAT','REVENUE','REVERSE','ROUTINE','RUNNING',
  'SATISFY','SCHOLAR','SECTION','SEGMENT','SERVICE','SESSION','SEVERAL','SHELTER',
  'SHORTLY','SILENCE','SKEPTIC','SKILLED','SOCIETY','SOLDIER','SOMEHOW','SPANISH',
  'SPEAKER','SPECIAL','SPONSOR','SQUEEZE','STADIUM','STATION','STORAGE','STRANGE',
  'STUDENT','SUBJECT','SUCCEED','SUCCESS','SUGGEST','SUMMARY','SUPPORT','SURFACE',
  'SURGEON','SURPLUS','SURVIVE','SUSTAIN','TEACHER','TENSION','THERAPY','THOUGHT',
  'TONIGHT','TOURIST','TRAFFIC','TRAINER','TROUBLE','TURNING','TYPICAL','UNIFORM',
  'UPGRADE','UTILITY','VARIETY','VEHICLE','VERSION','VETERAN','VICTORY','VILLAGE',
  'VIOLENT','VISIBLE','VOLCANO','WARFARE','WARNING','WEATHER','WEBSITE','WELCOME',
  'WELFARE','WESTERN','WHETHER','WHISPER','WILLING','WITNESS','WINNING','YOUNGER',
  // 8-letter words
  'ABSOLUTE','ABSTRACT','ACADEMIC','ACCURACY','ACCURATE','ACHIEVED','ACQUIRED',
  'ACTIVELY','ACTUALLY','ADDITION','ADEQUATE','ADVANCED','ADVOCATE','AFFECTED',
  'ALLIANCE','ALTHOUGH','ANALYSIS','ANNOUNCE','ANNUALLY','ANYTHING','ANYWHERE',
  'APPARENT','APPETITE','APPLAUSE','APPROACH','APPROVAL','ARGUMENT','ASSEMBLY',
  'ASSUMING','ATTACHED','BACHELOR','BACKWARD','BALANCED','BANKRUPT','BASEBALL',
  'BATHROOM','BECOMING','BIRTHDAY','BLANKING','BLESSING','BREAKING','BREEDING',
  'BRINGING','BUILDING','BULLETIN','BUSINESS','CAMPAIGN','CARRYING','CASUALLY',
  'CATEGORY','CEREMONY','CHAMPION','CHEMICAL','CHILDREN','CHOOSING','CIRCULAR',
  'CIVILIAN','CLIMBING','CLINICAL','CLOTHING','COACHING','COLLAPSE','COLONIAL',
  'COMBINED','COMEBACK','COMMENCE','COMMERCE','COMMONLY','COMMUNAL','COMPLETE',
  'COMPOSED','COMPOUND','COMPUTER','CONCLUDE','CONCRETE','CONFLICT','CONGRESS',
  'CONQUEST','CONSIDER','CONSTANT','CONSUMER','CONTINUE','CONTRACT','CONTRAST',
  'CONVINCE','CORRIDOR','COVERAGE','CREATIVE','CRIMINAL','CRITICAL','CROSSING',
  'CULTURAL','CURRENCY','CUSTOMER','DATABASE','DEADLINE','DECEMBER','DECISION',
  'DECLARED','DECLINED','DECREASE','DEDICATE','DEFENDER','DEFINITE','DELICATE',
  'DELIVERY','DEMOCRAT','DESCRIBE','DESIGNER','DESTINED','DETAILED','DIALOGUE',
  'DIRECTLY','DISASTER','DISCOUNT','DISCOVER','DISORDER','DISPOSAL','DISTANCE',
  'DISTINCT','DISTRICT','DOCTRINE','DOCUMENT','DOMESTIC','DOMINANT','DONATION',
  'DRAMATIC','DURATION','EARNINGS','ECONOMIC','EDUCATED','EFFICACY','EIGHTEEN',
  'ELECTION','ELECTRIC','ELEGANCE','ELEVATOR','ELIGIBLE','EMBEDDED','EMERGING',
  'EMISSION','EMPHASIS','EMPLOYED','EMPLOYEE','EMPLOYER','ENGAGING','ENGINEER',
  'ENORMOUS','ENSEMBLE','ENTIRELY','ENTITLED','ENTRANCE','ENVELOPE','EQUALITY',
  'EQUATION','ESTIMATE','EVALUATE','EVENTUAL','EVERYONE','EVIDENCE','EXCHANGE',
  'EXCITING','EXERCISE','EXISTING','EXPANDED','EXPECTED','EXPEDITE','EXPLICIT',
  'EXPLORED','EXPLORER','EXPORTED','EXPOSURE','EXTENDED','EXTERNAL','EXTRINSIC',
  'FACILITY','FAMILIAR','FAVORITE','FEATURED','FEEDBACK','FESTIVAL','FILENAME',
  'FINANCES','FINDINGS','FINISHED','FOLLOWED','FOOTNOTE','FORECAST','FORMERLY',
  'FORMULA','FOUNDING','FRACTION','FRAGMENT','FRANKLIN','FREQUENT','FRIENDLY',
  'FRONTIER','FUNCTION','GENERATE','GENOCIDE','GOVERNOR','GRADUATE','GRAPHICS',
  'GRATEFUL','GUARDIAN','GUIDANCE','HANDBOOK','HANDLING','HEADLINE','HERITAGE',
  'HOMELAND','HOMELESS','HOMEWORK','HONESTLY','HORRIBLE','HOSPITAL','HUMANITY',
  'IDENTIFY','IDEOLOGY','IGNORANT','ILLUSION','IMAGINED','IMMINENT','IMPERIAL',
  'IMPLICIT','IMPORTED','IMPOSING','IMPROVED','INCIDENT','INCLUDED','INCREASE',
  'INDICATE','INDIRECT','INDUSTRY','INFERIOR','INFINITE','INFORMAL','INFORMED',
  'INHERENT','INNOCENT','INSPIRED','INSTANCE','INTEGRAL','INTENDED','INTERACT',
  'INTEREST','INTERIOR','INTERNAL','INTERVAL','INTIMATE','INVASION','INVITING',
  'INVOLVED','ISOLATED','JUDGMENT','KEYBOARD','KNOCKOUT','LANDLORD','LANGUAGE',
  'LAUNCHED','LAUGHTER','LAWFULLY','LEARNING','LEFTOVER','LEVERAGE','LIFETIME',
  'LIKEWISE','LIMITING','LISTENER','LITERARY','LOCATION','MAGAZINE','MAGNETIC',
  'MAINTAIN','MAJORITY','MANAGING','MANIFEST','MARGINAL','MARRIAGE','MATERIAL',
  'MEASURED','MECHANIC','MEDICINE','MEMORIAL','MERCHANT','METAPHOR','MILITANT',
  'MILITARY','MINIMIZE','MINISTER','MINORITY','MODERATE','MOMENTUM','MONARCHY',
  'MONOPOLY','MOREOVER','MORTGAGE','MOVEMENT','MULTIPLE','MULTIPLY','MURDERER',
  'NATIONAL','NAVIGATE','NEGATIVE','NEIGHBOR','NERVOUS','NOTEBOOK','NUMEROUS',
  'OBJECTED','OBSERVER','OBSTACLE','OBTAINED','OCCASION','OCCUPIED','OFFERING',
  'OFFICIAL','OFFSHORE','OPPONENT','OPPOSITE','ORDINARY','ORGANISM','ORGANIZE',
  'ORIGINAL','OVERCOME','OVERHEAD','OVERLOOK','OVERSEAS','OVERTIME','OVERVIEW',
  'PAINTING','PARALLEL','PARTICLE','PATIENCE','PEACEFUL','PERCEIVE','PERSONAL',
  'PETITION','PLATFORM','PLEASANT','PLEASURE','PLUNGING','POLITICS','POLITICS',
  'POPULACE','POPULATE','PORTRAIT','POSITION','POSITIVE','POSSIBLE','POWERFUL',
  'PRACTICE','PRECIOUS','PREGNANT','PREMIERE','PREMISES','PRESENCE','PRESERVE',
  'PRESSURE','PRESTIGE','PREVIOUS','PRINCESS','PRINTING','PRIORITY','PRISONER',
  'PROBABLE','PRODUCER','PROFOUND','PROGRESS','PROHIBIT','PROPERLY','PROPERTY',
  'PROPOSAL','PROPOSED','PROSPECT','PROTOCOL','PROVINCE','PROVOKED','PUBLICLY',
  'PUNISHED','PURCHASE','PURSUING','QUANTITY','QUESTION','RATIONAL','REACTION',
  'READABLE','RECEIVED','RECENTLY','RECORDER','RECOVERY','REFERRAL','REFLECTED',
  'REGIONAL','REGISTER','REGULATE','RELATION','RELATIVE','RELEVANT','RELIABLE',
  'RELIGION','REMAINED','REMEMBER','RENOWNED','REPEATED','REPLACED','REPORTED',
  'REPUBLIC','REQUIRED','RESEARCH','RESIDENT','RESIGNED','RESOURCE','RESPONSE',
  'RESTLESS','RESTORED','RESTRICT','RESULTED','RETAILER','REVEALED','REVISION',
  'RHETORIC','ROMANTIC','SANCTION','SANDWICH','SCENARIO','SCHEDULE','SCRUTINY',
  'SEASONAL','SECURITY','SELECTED','SEMESTER','SENATOR','SEPARATE','SEQUENCE',
  'SERGEANT','SERVICES','SETTLING','SEVERITY','SHIPPING','SHOCKING','SHORTAGE',
  'SHOULDER','SHOWDOWN','SIDEWAYS','SILENTLY','SITUATED','SKETCHED','SLEEPING',
  'SLIGHTLY','SLIPPERY','SNAPSHOT','SOCALLED','SOFTWARE','SOLITARY','SOLUTION',
  'SOMEBODY','SOMEWHAT','SOUTHERN','SPEAKING','SPECIFIC','SPELLING','SPENDING',
  'SPORTING','SPOTLESS','SQUARELY','SQUEEZED','STAFFING','STAINING','STANDARD',
  'STANDING','STARTING','STEERING','STICKING','STIMULUS','STOPPING','STRAIGHT',
  'STRANGER','STRATEGY','STRENGTH','STRICTLY','STRIKING','STRONGLY','STRONGLY',
  'STRUGGLE','STUNNING','SUBURBAN','SUDDENLY','SUFFERED','SUITABLE','SUNLIGHT',
  'SUPPLIES','SUPPOSED','SUPREMEN','SURROUND','SURVIVAL','SUSPENSE','SYMPATHY',
  'TAILORED','TANGIBLE','TEACHING','TELEGRAM','TEMPLATE','TEMPORAL','TENDENCY',
  'TERMINAL','TERRIFIC','TERRIBLE','TEXTBOOK','THANKFUL','THEOLOGY','THINKING',
  'THOROUGH','THOUSAND','THRILLER','TOGETHER','TOMORROW','TOUCHING','TRACKING',
  'TRAINING','TRANSFER','TREASURE','TRIANGLE','TROPICAL','TROUBLED','TRUTHFUL',
  'ULTIMATE','UMBRELLA','UNDERWAY','UNLIKELY','UNSIGNED','UPDATING','UPHEAVAL',
  'UPCOMING','UPSTAIRS','VACATION','VALUABLE','VARIABLE','VELOCITY','VERTICAL',
  'VETERANS','VIOLATOR','VIOLENCE','VIRGINIA','VIRTUOUS','VISITING','VOLATILE',
  'OVERHEAD','WARRANTY','WATCHFUL','WEAKNESS','WEIGHING','WHATEVER','WHENEVER',
  'WHEREVER','WHISTLER','WILDFIRE','WILDLIFE','WIRELESS','WONDERED','WOODLAND',
  'WORKSHOP','WRAPPING','YEARBOOK','YIELDING',
]);

// ─── Local game state (we manage our own instead of using engine's submitWord
//     because the engine imports DICTIONARY which may not exist) ──────────────

type LocalFoundWord = { word: string; score: number };

interface LocalGameState {
  board: Board;
  foundWordsP1: Map<string, LocalFoundWord>;
  foundWordsP2: Map<string, LocalFoundWord>;
  scoreP1: number;
  scoreP2: number;
}

// ─── Phase management ──────────────────────────────────────────────────────
type Phase = 'modeSelect' | 'playing' | 'passDevice' | 'playingP2';

export default function BoggleScreen() {
  const { theme } = useTheme();
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { contentWidth, contentMaxWidth, height, isTablet } = useResponsive();
  // Width-bound on phones; on short/landscape screens keep the grid within ~55% of the height.
  const gridSize = Math.min(contentWidth - 48, isTablet ? 480 : 400, Math.max(240, height * 0.55));
  const cellSize = (gridSize - 24) / 4; // 4 cells with gaps

  // Mode & phase
  const { mode: modeParam } = useLocalSearchParams<{ mode: string }>();
  const resolvedMode = (modeParam === 'multiplayer' ? 'multiplayer' : 'single') as 'single' | 'multiplayer';

  const [mode, setMode] = useState<'single' | 'multiplayer'>(resolvedMode);
  const [phase, setPhase] = useState<Phase>('playing');

  // Game state
  const [gameState, setGameState] = useState<LocalGameState>(() => ({
    board: generateBoard(),
    foundWordsP1: new Map(),
    foundWordsP2: new Map(),
    scoreP1: 0,
    scoreP2: 0,
  }));
  const [currentInput, setCurrentInput] = useState('');
  // Cells tapped on the grid, in order. Empty while the player is typing instead.
  const [tapPath, setTapPath] = useState<Position[]>([]);
  const [feedback, setFeedback] = useState<{ text: string; isError: boolean } | null>(null);
  const [timeRemaining, setTimeRemaining] = useState(ROUND_DURATION_MS);
  const [isGameOver, setIsGameOver] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [resultRecorded, setResultRecorded] = useState(false);

  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const startTimeRef = useRef(Date.now());
  const inputRef = useRef<TextInput>(null);
  const feedbackTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const isSinglePlayer = mode === 'single';

  const clearWord = useCallback(() => {
    setCurrentInput('');
    setTapPath([]);
  }, []);

  // Typing replaces any tapped selection; the grid then highlights the typed word's path.
  const handleChangeText = useCallback((text: string) => {
    setCurrentInput(text);
    setTapPath([]);
  }, []);

  // Tap to build a word: adjacent cells extend it, the last cell undoes, an earlier
  // cell in the word rewinds to it, and any other cell starts a new word.
  const handleCellPress = useCallback(
    (row: number, col: number) => {
      if (isGameOver) return;
      const inPathAt = tapPath.findIndex((p) => p.row === row && p.col === col);
      const last = tapPath[tapPath.length - 1];
      let next: Position[];
      if (inPathAt === tapPath.length - 1 && inPathAt >= 0) {
        next = tapPath.slice(0, -1);
      } else if (inPathAt >= 0) {
        next = tapPath.slice(0, inPathAt + 1);
      } else if (last && Math.abs(last.row - row) <= 1 && Math.abs(last.col - col) <= 1) {
        next = [...tapPath, { row, col }];
      } else {
        next = [{ row, col }];
      }
      haptics.selection();
      setTapPath(next);
      setCurrentInput(next.map((p) => gameState.board[p.row][p.col]).join(''));
    },
    [isGameOver, tapPath, gameState.board],
  );

  const highlightedPath = useMemo(() => {
    if (tapPath.length > 0) return tapPath;
    const typed = currentInput.trim().toUpperCase();
    return typed ? traceWord(gameState.board, typed) ?? [] : [];
  }, [tapPath, currentInput, gameState.board]);
  const currentPlayer = phase === 'playingP2' ? 'player2' : 'player1';

  // ── Derived data ─────────────────────────────────────────────────────────
  const currentFoundWords = gameState
    ? currentPlayer === 'player1'
      ? gameState.foundWordsP1
      : gameState.foundWordsP2
    : new Map<string, LocalFoundWord>();

  const currentScore = gameState
    ? currentPlayer === 'player1'
      ? gameState.scoreP1
      : gameState.scoreP2
    : 0;

  const foundWordsArray = Array.from(currentFoundWords.values()).reverse();

  // ── Timer ────────────────────────────────────────────────────────────────
  const stopTimer = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
  }, []);

  const startTimer = useCallback(() => {
    stopTimer();
    const start = Date.now();
    setTimeRemaining(ROUND_DURATION_MS);
    timerRef.current = setInterval(() => {
      const elapsed = Date.now() - start;
      const remaining = Math.max(0, ROUND_DURATION_MS - elapsed);
      setTimeRemaining(remaining);
      if (remaining <= 0) {
        stopTimer();
      }
    }, 100);
  }, [stopTimer]);

  // When timer hits 0, handle round end
  useEffect(() => {
    if (timeRemaining <= 0 && gameState && !isGameOver) {
      if (phase === 'playing' && mode === 'multiplayer') {
        // Player 1 done, switch to pass device
        stopTimer();
        setPhase('passDevice');
        clearWord();
        setFeedback(null);
      } else {
        // Single player done, or Player 2 done
        stopTimer();
        setIsGameOver(true);
      }
    }
  }, [timeRemaining, gameState, isGameOver, phase, mode, stopTimer]);

  // Start timer on mount since game begins immediately
  useEffect(() => {
    const start = Date.now();
    startTimeRef.current = start;
    setTimeRemaining(ROUND_DURATION_MS);
    timerRef.current = setInterval(() => {
      const elapsed = Date.now() - start;
      const remaining = Math.max(0, ROUND_DURATION_MS - elapsed);
      setTimeRemaining(remaining);
      if (remaining <= 0) {
        clearInterval(timerRef.current!);
        timerRef.current = null;
      }
    }, 100);
  }, []);

  // Clean up timer on unmount
  useEffect(() => {
    return () => {
      stopTimer();
      if (feedbackTimeoutRef.current) clearTimeout(feedbackTimeoutRef.current);
    };
  }, [stopTimer]);

  // ── Show feedback temporarily ────────────────────────────────────────────
  const showFeedback = useCallback((text: string, isError: boolean) => {
    if (feedbackTimeoutRef.current) clearTimeout(feedbackTimeoutRef.current);
    setFeedback({ text, isError });
    feedbackTimeoutRef.current = setTimeout(() => {
      setFeedback(null);
    }, 2000);
  }, []);

  // ── Pass device -> Player 2 starts ──────────────────────────────────────
  const handlePassReady = useCallback(() => {
    setPhase('playingP2');
    clearWord();
    setFeedback(null);
    startTimer();
  }, [startTimer]);

  // ── Submit word ──────────────────────────────────────────────────────────
  const handleSubmitWord = useCallback(() => {
    if (!gameState || isGameOver) return;

    const word = currentInput.trim().toUpperCase();
    const wasTapped = tapPath.length > 0;
    clearWord();

    if (word.length < 3) {
      showFeedback('Word must be at least 3 letters', true);
      return;
    }

    if (!FALLBACK_DICTIONARY.has(word)) {
      showFeedback('Not a word', true);
      return;
    }

    const words = currentPlayer === 'player1'
      ? gameState.foundWordsP1
      : gameState.foundWordsP2;

    if (words.has(word)) {
      showFeedback('Already found', true);
      return;
    }

    if (!canTraceWord(gameState.board, word)) {
      showFeedback("Can't trace on board", true);
      return;
    }

    const score = calculateScore(word.length);
    const newWords = new Map(words);
    newWords.set(word, { word, score });

    if (currentPlayer === 'player1') {
      setGameState({
        ...gameState,
        foundWordsP1: newWords,
        scoreP1: gameState.scoreP1 + score,
      });
    } else {
      setGameState({
        ...gameState,
        foundWordsP2: newWords,
        scoreP2: gameState.scoreP2 + score,
      });
    }

    showFeedback(`+${score} point${score > 1 ? 's' : ''}!`, false);
    // Keep the keyboard up for typists; don't pop it open for players who tap.
    if (!wasTapped) inputRef.current?.focus();
  }, [gameState, isGameOver, currentInput, tapPath, currentPlayer, showFeedback, clearWord]);

  // ── Game over handling ───────────────────────────────────────────────────
  useEffect(() => {
    if (isGameOver && gameState && !resultRecorded) {
      setResultRecorded(true);

      const durationSeconds = Math.round(
        (Date.now() - startTimeRef.current) / 1000,
      );

      if (isSinglePlayer) {
        recordGameResult({
          game: 'boggle',
          mode: 'single',
          player: 'Player',
          score: gameState.scoreP1,
          result: gameState.scoreP1 > 0 ? 'win' : 'draw',
          durationSeconds,
        });
      } else {
        const p1 = gameState.scoreP1;
        const p2 = gameState.scoreP2;
        // One record per game (like the other games): the winner, or a single draw.
        recordGameResult({
          game: 'boggle',
          mode: 'multiplayer',
          player: p1 >= p2 ? 'Player 1' : 'Player 2',
          score: Math.max(p1, p2),
          result: p1 === p2 ? 'draw' : 'win',
          durationSeconds,
        });
      }

      const timeout = setTimeout(() => setShowModal(true), 600);
      return () => clearTimeout(timeout);
    }
  }, [isGameOver]);

  // ── Rematch / Home ───────────────────────────────────────────────────────
  const handleRematch = useCallback(() => {
    setShowModal(false);
    setResultRecorded(false);
    setIsGameOver(false);
    clearWord();
    setFeedback(null);
    stopTimer();

    const board = mode === 'multiplayer' ? gameState?.board ?? generateBoard() : generateBoard();
    setGameState({
      board: generateBoard(),
      foundWordsP1: new Map(),
      foundWordsP2: new Map(),
      scoreP1: 0,
      scoreP2: 0,
    });
    setPhase('playing');
    startTimeRef.current = Date.now();
    setTimeout(() => {
      const start = Date.now();
      setTimeRemaining(ROUND_DURATION_MS);
      timerRef.current = setInterval(() => {
        const elapsed = Date.now() - start;
        const remaining = Math.max(0, ROUND_DURATION_MS - elapsed);
        setTimeRemaining(remaining);
        if (remaining <= 0) {
          clearInterval(timerRef.current!);
          timerRef.current = null;
        }
      }, 100);
    }, 50);
  }, [mode, stopTimer]);

  const handleHome = useCallback(() => {
    setShowModal(false);
    stopTimer();
    router.back();
  }, [router, stopTimer]);

  // ── Modal result ─────────────────────────────────────────────────────────
  const getModalResult = () => {
    if (!gameState) return { winner: 'draw' as const };
    if (isSinglePlayer) {
      return {
        winner: 'player1' as const,
        score: { player1: gameState.scoreP1, player2: 0 },
      };
    }
    const p1 = gameState.scoreP1;
    const p2 = gameState.scoreP2;
    if (p1 > p2) return { winner: 'player1' as const, score: { player1: p1, player2: p2 } };
    if (p2 > p1) return { winner: 'player2' as const, score: { player1: p1, player2: p2 } };
    return { winner: 'draw' as const, score: { player1: p1, player2: p2 } };
  };

  // ── Format time ──────────────────────────────────────────────────────────
  const formatTime = (ms: number) => {
    const totalSeconds = Math.ceil(ms / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
  };

  const timerProgress = timeRemaining / ROUND_DURATION_MS;
  const timerColor =
    timerProgress > 0.5
      ? theme.colors.success
      : timerProgress > 0.2
      ? '#F59E0B'
      : theme.colors.error;

  const isPlaying = phase === 'playing' || phase === 'playingP2';

  // ─── RENDER ──────────────────────────────────────────────────────────────
  return (
    <View style={[styles.container, { backgroundColor: theme.colors.background, maxWidth: contentMaxWidth }]}>
      <Stack.Screen
        options={{
          headerShown: true,
          title: 'Word Grid',
          headerStyle: { backgroundColor: theme.colors.surface },
          headerTintColor: theme.colors.text,
          headerLeft: () => (
            <Pressable onPress={() => { stopTimer(); router.back(); }} style={styles.backButton}>
              <Animated.Text style={{ color: theme.colors.text, fontSize: 16 }}>
                ← Back
              </Animated.Text>
            </Pressable>
          ),
        }}
      />

      {/* ── Pass Device (2P) ────────────────────────────────────────────── */}
      {phase === 'passDevice' && (
        <View style={styles.centeredPhase}>
          <ThemedText variant="heading" style={styles.phaseTitle}>
            Player 1 finished!
          </ThemedText>
          <ThemedText
            variant="body"
            style={[styles.phaseSubtitle, { color: theme.colors.textMuted }]}
          >
            Score: {gameState?.scoreP1 ?? 0} points
          </ThemedText>
          <ThemedText
            variant="body"
            style={[styles.phaseSubtitle, { color: theme.colors.textMuted }]}
          >
            Pass the device to Player 2.{'\n'}Same board, 2 minutes.
          </ThemedText>
          <View style={{ marginTop: 24, width: '100%', maxWidth: 260 }}>
            <Button title="Ready" onPress={handlePassReady} variant="primary" size="lg" />
          </View>
        </View>
      )}

      {/* ── Playing ─────────────────────────────────────────────────────── */}
      {isPlaying && gameState && (
        <ScrollView
          contentContainerStyle={[
            styles.playContent,
            { paddingBottom: insets.bottom + 16 },
          ]}
          bounces={false}
          keyboardShouldPersistTaps="handled"
        >
          {/* Player indicator (2P) */}
          {!isSinglePlayer && (
            <View style={[styles.playerBadge, {
              backgroundColor: (currentPlayer === 'player1' ? theme.colors.player1 : theme.colors.player2) + '20',
              borderRadius: theme.borderRadius.sm,
            }]}>
              <ThemedText
                variant="label"
                style={{
                  color: currentPlayer === 'player1' ? theme.colors.player1 : theme.colors.player2,
                  fontWeight: '700',
                }}
              >
                {currentPlayer === 'player1' ? 'Player 1' : 'Player 2'}
              </ThemedText>
            </View>
          )}

          {/* Timer bar */}
          <View style={[styles.timerContainer, {
            backgroundColor: theme.colors.surface,
            borderRadius: theme.borderRadius.sm,
          }]}>
            <View style={styles.timerHeader}>
              <ThemedText variant="label" style={{ color: timerColor, fontWeight: '700' }}>
                {formatTime(timeRemaining)}
              </ThemedText>
              <ThemedText variant="label" style={{ color: theme.colors.text, fontWeight: '700' }}>
                Score: {currentScore}
              </ThemedText>
            </View>
            <View style={[styles.timerBarBackground, {
              backgroundColor: theme.colors.border,
              borderRadius: theme.borderRadius.sm,
            }]}>
              <View style={[styles.timerBarFill, {
                backgroundColor: timerColor,
                borderRadius: theme.borderRadius.sm,
                width: `${timerProgress * 100}%`,
              }]} />
            </View>
          </View>

          {/* Board grid */}
          <Animated.View
            entering={FadeIn.duration(300)}
            style={[styles.boardContainer, {
              backgroundColor: theme.colors.surface,
              borderRadius: theme.borderRadius.lg,
              ...theme.shadows.md,
            }]}
          >
            {gameState.board.map((row, r) => (
              <View key={r} style={styles.boardRow}>
                {row.map((letter, c) => {
                  const pathIndex = highlightedPath.findIndex((p) => p.row === r && p.col === c);
                  const selected = pathIndex >= 0;
                  const isLast = selected && pathIndex === highlightedPath.length - 1;
                  return (
                  <Pressable
                    key={`${r}-${c}`}
                    onPress={() => handleCellPress(r, c)}
                    disabled={isGameOver}
                    accessibilityRole="button"
                    accessibilityLabel={`Letter ${letter}${selected ? ', selected' : ''}`}
                    style={({ pressed }) => [styles.cell, {
                      backgroundColor: isLast
                        ? theme.colors.primary
                        : selected
                          ? theme.colors.primary + '30'
                          : theme.colors.background,
                      borderColor: selected ? theme.colors.primary : theme.colors.border,
                      borderRadius: theme.borderRadius.md,
                      width: cellSize,
                      height: cellSize,
                      transform: [{ scale: pressed ? 0.94 : 1 }],
                    }]}
                  >
                    <ThemedText
                      variant="heading"
                      style={[
                        styles.cellLetter,
                        { color: isLast ? '#FFFFFF' : theme.colors.text, fontSize: Math.max(20, cellSize * 0.34) },
                      ]}
                    >
                      {letter}
                    </ThemedText>
                    {letter.length > 1 && (
                      <View style={[styles.quBadge, { backgroundColor: theme.colors.primary + '20' }]}>
                        <ThemedText variant="caption" style={{ color: theme.colors.primary, fontSize: 8 }}>
                          2
                        </ThemedText>
                      </View>
                    )}
                  </Pressable>
                  );
                })}
              </View>
            ))}
          </Animated.View>

          {/* Word input */}
          <View style={styles.inputRow}>
            <TextInput
              ref={inputRef}
              value={currentInput}
              onChangeText={handleChangeText}
              placeholder="Type or tap letters..."
              placeholderTextColor={theme.colors.textMuted}
              autoCapitalize="characters"
              autoCorrect={false}
              editable={!isGameOver}
              onSubmitEditing={handleSubmitWord}
              returnKeyType="done"
              style={[styles.textInput, {
                color: theme.colors.text,
                borderColor: theme.colors.border,
                backgroundColor: theme.colors.surface,
                borderRadius: theme.borderRadius.md,
                fontFamily: theme.fonts.body,
              }]}
            />
            {currentInput.length > 0 && !isGameOver && (
              <Pressable onPress={clearWord} hitSlop={8} accessibilityLabel="Clear word" style={styles.clearButton}>
                <ThemedText variant="body" style={{ color: theme.colors.textMuted }}>✕</ThemedText>
              </Pressable>
            )}
            <View style={{ width: 80 }}>
              <Button
                title="Submit"
                onPress={handleSubmitWord}
                variant="primary"
                size="md"
                disabled={isGameOver || currentInput.trim().length === 0}
              />
            </View>
          </View>

          {/* Feedback */}
          {feedback && (
            <Animated.View
              entering={FadeIn.duration(150)}
              style={[styles.feedbackContainer, {
                backgroundColor: feedback.isError
                  ? theme.colors.error + '18'
                  : theme.colors.success + '18',
                borderRadius: theme.borderRadius.sm,
              }]}
            >
              <ThemedText
                variant="label"
                style={{
                  color: feedback.isError ? theme.colors.error : theme.colors.success,
                  fontWeight: '600',
                  textAlign: 'center',
                }}
              >
                {feedback.text}
              </ThemedText>
            </Animated.View>
          )}

          {/* Scoring reference */}
          <View style={[styles.scoringRef, {
            backgroundColor: theme.colors.surface,
            borderRadius: theme.borderRadius.sm,
          }]}>
            <ThemedText variant="caption" style={{ color: theme.colors.textMuted }}>
              3-4 letters: 1pt {'  '} 5: 2pt {'  '} 6: 3pt {'  '} 7: 5pt {'  '} 8+: 11pt
            </ThemedText>
          </View>

          {/* Found words list */}
          {foundWordsArray.length > 0 && (
            <View style={[styles.foundWordsContainer, {
              backgroundColor: theme.colors.surface,
              borderRadius: theme.borderRadius.md,
            }]}>
              <ThemedText
                variant="label"
                style={[styles.foundWordsTitle, { color: theme.colors.textMuted }]}
              >
                Found Words ({foundWordsArray.length})
              </ThemedText>
              <View style={styles.foundWordsList}>
                {foundWordsArray.map((fw) => (
                  <View
                    key={fw.word}
                    style={[styles.foundWordChip, {
                      backgroundColor: theme.colors.primary + '15',
                      borderRadius: theme.borderRadius.sm,
                    }]}
                  >
                    <ThemedText variant="caption" style={{ color: theme.colors.text, fontWeight: '600' }}>
                      {fw.word}
                    </ThemedText>
                    <ThemedText variant="caption" style={{ color: theme.colors.primary, fontWeight: '700', marginLeft: 4 }}>
                      +{fw.score}
                    </ThemedText>
                  </View>
                ))}
              </View>
            </View>
          )}

          {/* Time's up overlay */}
          {isGameOver && (
            <Animated.View
              entering={FadeIn.duration(300)}
              style={[styles.timesUpBanner, {
                backgroundColor: theme.colors.error + '15',
                borderRadius: theme.borderRadius.md,
              }]}
            >
              <ThemedText variant="heading" style={{ color: theme.colors.error, textAlign: 'center' }}>
                Time's Up!
              </ThemedText>
              {isSinglePlayer ? (
                <ThemedText variant="body" style={{ color: theme.colors.text, textAlign: 'center', marginTop: 4 }}>
                  Final Score: {gameState.scoreP1}
                </ThemedText>
              ) : (
                <View style={{ marginTop: 8 }}>
                  <ThemedText variant="body" style={{ color: theme.colors.player1, textAlign: 'center' }}>
                    Player 1: {gameState.scoreP1}
                  </ThemedText>
                  <ThemedText variant="body" style={{ color: theme.colors.player2, textAlign: 'center' }}>
                    Player 2: {gameState.scoreP2}
                  </ThemedText>
                </View>
              )}
            </Animated.View>
          )}
        </ScrollView>
      )}

      {/* ── Game Over Modal ─────────────────────────────────────────────── */}
      <GameOverModal
        visible={showModal}
        result={getModalResult()}
        onRematch={handleRematch}
        onHome={handleHome}
        gameName="Word Grid"
      />
    </View>
  );
}

// ─── Styles ────────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignSelf: 'center' as const,
    width: '100%' as const,
  },
  backButton: {
    padding: 8,
    marginLeft: -4,
  },

  // Phase screens
  centeredPhase: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  phaseTitle: {
    textAlign: 'center',
    marginBottom: 8,
  },
  phaseSubtitle: {
    textAlign: 'center',
    marginBottom: 8,
  },

  // Playing screen
  playContent: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
  },

  // Player badge
  playerBadge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 8,
  },

  // Timer
  timerContainer: {
    width: '100%',
    padding: 12,
    marginBottom: 12,
  },
  timerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  timerBarBackground: {
    width: '100%',
    height: 8,
    overflow: 'hidden',
  },
  timerBarFill: {
    height: '100%',
  },

  // Board
  boardContainer: {
    padding: 12,
    marginBottom: 12,
  },
  boardRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  cell: {
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  clearButton: {
    paddingHorizontal: 4,
    justifyContent: 'center',
  },
  cellLetter: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  quBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Input
  inputRow: {
    flexDirection: 'row',
    width: '100%',
    gap: 8,
    marginBottom: 8,
    alignItems: 'center',
  },
  textInput: {
    flex: 1,
    minWidth: 0,
    height: 48,
    borderWidth: 2,
    paddingHorizontal: 16,
    fontSize: 18,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },

  // Feedback
  feedbackContainer: {
    width: '100%',
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 8,
  },

  // Scoring reference
  scoringRef: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 12,
  },

  // Found words
  foundWordsContainer: {
    width: '100%',
    padding: 12,
    marginBottom: 12,
  },
  foundWordsTitle: {
    marginBottom: 8,
    fontWeight: '600',
  },
  foundWordsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  foundWordChip: {
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
  },

  // Time's up
  timesUpBanner: {
    width: '100%',
    padding: 20,
    marginBottom: 12,
  },
});
